---
- hosts: all
  vars:
    user_details:
        - { name: 'Annabelle' }
        - { name: 'Bob'  }
        - { name: 'Carl'  }
        - { name: 'Dyson'  }
        - { name: 'Evert'  }
        - { name: 'Frank'  }
        - { name: 'Gerry'  }
        - { name: 'Harold'  }
        - { name: 'Isabella'  }
        - { name: 'Jameson'  }
  become: true
  tasks:
    - name: test
      ansible.builtin.ping:
#   - name: more complex items to add several users
#     user:
#       name: "{{ item.name }}"
#       password: '“@#FD12”'
#       state: present
#     with_items: "{{ user_details }}"

#   - name: Set authorized key
#     ansible.posix.authorized_key:
#       user: "{{ item.name }}"
#       state: present
#       key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK"
#     with_items: "{{ user_details }}"
...
